// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/ATenderholt/rainbow/internal/http"
	"github.com/ATenderholt/rainbow/internal/service"
	"github.com/ATenderholt/rainbow/settings"
	"github.com/go-rel/rel"
	"github.com/go-rel/sqlite3"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from inject.go:

func InjectApp(cfg *settings.Config, db *sql.DB) (App, error) {
	repository := InjectDb(db)
	motoService := service.NewMotoService(repository)
	elasticService := service.NewElasticService(repository)
	proxy := http.NewProxy(cfg)
	mux := http.NewChiMux(motoService, elasticService, proxy)
	app := NewApp(cfg, mux)
	return app, nil
}

// inject.go:

func InjectDb(db *sql.DB) rel.Repository {
	adapter := sqlite3.New(db)
	return rel.New(adapter)
}
