// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ATenderholt/rainbow/internal/http"
	"github.com/ATenderholt/rainbow/settings"
	"github.com/google/wire"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from inject.go:

func InjectApp(cfg *settings.Config) (App, error) {
	serviceRouter := http.NewServiceRouter()
	mux := http.NewChiMux(serviceRouter)
	app := NewApp(cfg, mux)
	return app, nil
}

// inject.go:

var api = wire.NewSet(http.NewChiMux, http.NewServiceRouter)
